<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../style.css">
    <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" href="../vendor/fontawesome/css/solid.min.css">

    <title>Cadastro</title>
</head>

<body class="row">

    <div class="container">
        
        <nav>
            <a href="/home/">Home</a>
            <a href="/cadastro/">Cadastro</a>
            <a href="/lista/">Lista de Carros</a>
            <a href="/atualizar/">Atualizar Lista</a>
        </nav>
 
        <form action="/cadastro/" method="post">
            
            <div>
                <h2> <span class="label label-default">Modelo:</span></h2>
                <input placeholder=" Insira o modelo do carro" type="text" name="modelo" require>
            </div>
            <div>
                <h2> <span class="label label-default">Marca:</span></h2>
                <input placeholder=" Insira a marca do carro" type="text" name="marca" require>
            </div>
            <div>
                <h2> <span class="label label-default">Ano:</span></h2>
                <input placeholder=" Insira o ano do carro" type="text" name="ano" require>
            </div>
            <div>
                <h2> <span class="label label-default">Dono:</span></h2>
                <input placeholder=" Insira o ano do carro" type="text" name="dono" require>
            </div>
                
            
            <input type="submit" value="Enviar">

        </form>

    </div>

</body>

<script src="/vendor/jquery/jquery-3.4.1.min.js"></script>
<script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


</html>
